# Generated by Django 5.1.2 on 2024-10-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlepost",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
